### ISSUE TITLE
USB-C Gadget mode

### ISSUE THREAD

**Issue by lawik** [nerves-project/nerves_system_rpi4#18]
To my knowledge we currently don't have USB-C gadget mode for the Pi 4. [This post](https://www.hardill.me.uk/wordpress/2019/11/02/pi4-usb-c-gadget/) seems to say that's possible. So that would be neat. I guess it might even get enough power :)

**Comment by fhunleth** [comment]
I agree - it looked possible when I was doing the original port. I wasn't sure about power, but I guess it doesn't hurt to try.

**Comment by lawik** [comment]
I imagine it should work on decently powerful laptops, blog post sure makes it look like it works. I'm guessing it can negotiate something more juicy than the ol' micro-USB gadgets could.

**Comment by lucaong** [comment]
I tried, as an experiment, to emulate a USB HID device (keyboard) on Nerves Rpi4 by following the indications in [this post](http://www.isticktoit.net/?p=1383), originally written for the Zero on Raspbian and basically similar to the post linked above.

I loaded the `dwc2` and `libcomposite` modules, and had to manually mount ConfigFS with `mount none /sys/kernel/config -t configfs`. Still, the problem is that `ls /sys/class/udc` gives empty results, so something is clearly missing but I don't know what.

Any idea about what would be needed to get that to work?

I see other efforts to get ConfigFS to work on some Pi models, like https://github.com/nerves-project/nerves_system_rpi0/pull/62

It would be really great to be able to use the Rpi4 USB-C in device mode.

**Comment by lucaong** [comment]
An update to this, I managed to fix this issue by adding the `dwc2` device tree with a custom `fwup.conf` like it's done here on the RPi Zero: https://github.com/nerves-project/nerves_system_rpi0/blob/master/fwup.conf#L229

Now the USB Device Controller is properly populated in `/sys/class/udc` and the `/dev/hidg0` device appears. The problem is that, when I try to write HID reports to `/dev/hidg0`, the write operation hangs. Any idea?

I'd be very happy to share my proof-of-concept if I get it to work end to end.

**Comment by lucaong** [comment]
I figured it out, the HID report description was wrong. Now it works fine.

Here is a (hacky but working) proof of concept of the RPi4 on standard Nerves using the USB-C in gadget mode (emulating a USB Keyboard): https://github.com/lucaong/nerves_rpi4_hid_gadget_poc

Ideally one would use `nerves/usb_gadget` instead of the custom shell script to create and setup the USB gadget.

**Comment by lawik** [comment]
So this would make it pretty likely that we could do the ethernet gadget or whatever the pi0 does to provide SSH over the wire by default?

**Comment by lucaong** [comment]
That definitely sounds possible.
