### ISSUE TITLE
Increasing uboot size

### ISSUE THREAD

**Issue by igormq** [nerves-project/nerves_system_rpi4#53]
### Current behavior

I couldn't change to any value in fwup.conf for "UBOOT_ENV_COUNT" that works
 
### Expected behavior

I should be able to increase uboot size!

**Comment by ConnorRigby** [comment]
We may need a bit more information. What exactly did you do to observe this? My initial suspicion is that you increased that variable, but tried an `upgrade` instead of `complete` task.

**Comment by igormq** [comment]
Sure, sorry about that.

I am trying to inscrease the uboot size by setting the following in `fwup.conf`

```
define(UBOOT_ENV_OFFSET, 16)
define(UBOOT_ENV_COUNT, 32)  # 16 KB
```

Then I run `mix firmware` and `mix burn -t complete` and in my rpi4 the following occur:

```elixir
iex(1)> Nerves.Runtime.KV.get_all
%{
  "baudrate" => "115200",
  "bootcmd" => "bootp; setenv bootargs root=/dev/nfs nfsroot=${serverip}:${rootpath} ip=${ipaddr}:${serverip}:${gatewayip}:${netmask}:${hostname}::off; bootm",
  "bootdelay" => "5"
}
```

I would expect that all my uboot env vars will be available (such as `a.*` vars and so on), but as one can see the envs are missing!

Thanks!

**Comment by fhunleth** [comment]
U-Boot size is also set here: https://github.com/nerves-project/nerves_system_rpi4/blob/main/rootfs_overlay/etc/fw_env.config#L9

If you're going to increase it, could you pick 128 KB (256 blocks in the fwup config)? The small size we have in Nerves is due to a mistake I made several years ago that we can't fix in a backwards compatible way. When we make major version bumps, I'm been switching to 128 KB environment sizes.

**Comment by igormq** [comment]
Thank you a lot. It worked as expected! :+1:
